In [ ]:
# Vectorization is process of maniplating each and every element of an array without using loops.

In [2]:
import pandas as pd
data = {
    "name": ["A", "B", "C", "D"],
    "department": ["IT", "HR", "IT", "Sales"],
    "salary": [50000, 40000, 55000, 45000],
    "experience": [2, 1, 3, 2]
}
df = pd.DataFrame(data)
df

  name department  salary  experience
0    A         IT   50000           2
1    B         HR   40000           1
2    C         IT   55000           3
3    D      Sales   45000           2

In [3]:
df.shape

(4, 4)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        4 non-null      str
 1   department  4 non-null      str
 2   salary      4 non-null      int64
 3   experience  4 non-null      int64
dtypes: int64(2), str(2)
memory usage: 260.0 bytes

In [5]:
df.describe()

             salary  experience
count      4.000000    4.000000
mean   47500.000000    2.000000
std     6454.972244    0.816497
min    40000.000000    1.000000
25%    43750.000000    1.750000
50%    47500.000000    2.000000
75%    51250.000000    2.250000
max    55000.000000    3.000000

In [7]:
df.columns

Index(['name', 'department', 'salary', 'experience'], dtype='str')

In [8]:
df['salary']

0    50000
1    40000
2    55000
3    45000
Name: salary, dtype: int64

In [10]:
df[['name','salary']]

  name  salary
0    A   50000
1    B   40000
2    C   55000
3    D   45000

In [11]:
df[df['salary']>45000]

  name department  salary  experience
0    A         IT   50000           2
2    C         IT   55000           3

In [14]:
df[(df['department'] == 'IT') & (df['experience'] >=2)]

  name department  salary  experience
0    A         IT   50000           2
2    C         IT   55000           3

In [15]:
df.groupby('department')['salary'].mean()

department
HR       40000.0
IT       52500.0
Sales    45000.0
Name: salary, dtype: float64

In [16]:
df.groupby('department').agg({'salary':['mean','max'],'experience':'mean'})

             salary        experience
               mean    max       mean
department
HR          40000.0  40000        1.0
IT          52500.0  55000        2.5
Sales       45000.0  45000        2.0

In [17]:
df.sort_values('salary',ascending=False)

  name department  salary  experience
2    C         IT   55000           3
0    A         IT   50000           2
3    D      Sales   45000           2
1    B         HR   40000           1

In [18]:
df.sort_values('salary')

  name department  salary  experience
1    B         HR   40000           1
3    D      Sales   45000           2
0    A         IT   50000           2
2    C         IT   55000           3

In [20]:
df.loc[2,'salary'] = None
df

  name department   salary  experience
0    A         IT  50000.0           2
1    B         HR  40000.0           1
2    C         IT      NaN           3
3    D      Sales  45000.0           2

In [21]:
df['salary'].fillna(df['salary'].mean(),inplace = True)

C:\Users\susha\AppData\Local\Temp\ipykernel_11160\3829682045.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['salary'].fillna(df['salary'].mean(),inplace = True)

0    50000.0
1    40000.0
2    45000.0
3    45000.0
Name: salary, dtype: float64

In [23]:
data1 = {
    "student": ["A", "B", "C", "D", "E"],
    "marks": [78, 45, None, 89, 60],
    "subject": ["Math", "Math", "Math", "Math", "Math"]
}
df1 = pd.DataFrame(data1)
df1

  student  marks subject
0       A   78.0    Math
1       B   45.0    Math
2       C    NaN    Math
3       D   89.0    Math
4       E   60.0    Math

In [36]:
df1['marks'] = df1['marks'].fillna(df1['marks'].mean(),inplace = True)
df1['marks']

C:\Users\susha\AppData\Local\Temp\ipykernel_11160\2896674149.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df1['marks'] = df1['marks'].fillna(df1['marks'].mean(),inplace = True)

0    78.0
1    45.0
2    68.0
3    89.0
4    60.0
Name: marks, dtype: float64

In [39]:
import numpy as np
df1['result'] = np.where(df1['marks'] >= 50,'pass','fail')

df1

  student  marks subject result
0       A   78.0    Math   pass
1       B   45.0    Math   fail
2       C   68.0    Math   pass
3       D   89.0    Math   pass
4       E   60.0    Math   pass

In [41]:
print("Averge_marks:",np.mean(df1['marks']))

Averge_marks: 68.0

In [45]:
pass_percentage = ((df1['marks']>=50).mean()*100)
print(pass_percentage)

80.0